#ifndef AVI_EMBEDDED_H
#define AVI_EMBEDDED_H

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct AVI_AviEmbedded AVI_AviEmbedded;

typedef struct AVI_AviEmbeddedConfig {
    uint64_t device_id;
} AVI_AviEmbeddedConfig;

typedef int32_t (*AVI_CUdpSendCallback)(void *user_data, const uint8_t *buf, uintptr_t len);

typedef int32_t (*AVI_CUdpReceiveCallback)(void *user_data, uint8_t *buf, uintptr_t buf_len);

typedef void (*AVI_CMessageCallback)(void *user_data, const char *topic, uintptr_t topic_len, const uint8_t *data, uintptr_t data_len);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void avi_embedded_init(void);

struct AVI_AviEmbedded *avi_embedded_new(struct AVI_AviEmbeddedConfig config, uint8_t *buffer, uintptr_t buffer_len, void *udp_user_data, AVI_CUdpSendCallback udp_send_fn, AVI_CUdpReceiveCallback udp_recv_fn, void *msg_user_data, AVI_CMessageCallback msg_callback);

void avi_embedded_free(struct AVI_AviEmbedded *avi);

int32_t avi_embedded_connect(struct AVI_AviEmbedded *avi);

bool avi_embedded_is_connected(const struct AVI_AviEmbedded *avi);

int32_t avi_embedded_subscribe(struct AVI_AviEmbedded *avi, const char *topic, uintptr_t topic_len);

int32_t avi_embedded_unsubscribe(struct AVI_AviEmbedded *avi, const char *topic, uintptr_t topic_len);

int32_t avi_embedded_publish(struct AVI_AviEmbedded *avi, const char *topic, uintptr_t topic_len, const uint8_t *data, uintptr_t data_len);

int32_t avi_embedded_start_stream(struct AVI_AviEmbedded *avi, uint8_t local_stream_id, const char *target_peer_id, uintptr_t target_peer_id_len, const char *reason, uintptr_t reason_len);

int32_t avi_embedded_send_stream_data(struct AVI_AviEmbedded *avi, uint8_t local_stream_id, const uint8_t *data, uintptr_t data_len);

int32_t avi_embedded_close_stream(struct AVI_AviEmbedded *avi, uint8_t local_stream_id);

int32_t avi_embedded_button_pressed(struct AVI_AviEmbedded *avi, uint8_t button_id, uint8_t press_type);

int32_t avi_embedded_update_sensor_temperature(struct AVI_AviEmbedded *avi, const char *sensor_name, uintptr_t sensor_name_len, float value);

int32_t avi_embedded_update_sensor_humidity(struct AVI_AviEmbedded *avi, const char *sensor_name, uintptr_t sensor_name_len, float value);

int32_t avi_embedded_update_sensor_battery(struct AVI_AviEmbedded *avi, const char *sensor_name, uintptr_t sensor_name_len, uint8_t value);

int32_t avi_embedded_update_sensor_status(struct AVI_AviEmbedded *avi, const char *sensor_name, uintptr_t sensor_name_len, bool value);

int32_t avi_embedded_update_sensor_raw(struct AVI_AviEmbedded *avi, const char *sensor_name, uintptr_t sensor_name_len, int32_t value);

int32_t avi_embedded_poll(struct AVI_AviEmbedded *avi);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AVI_EMBEDDED_H */
